### PR TITLE
Fix rich comparison functions of Individual

### PR DESCRIPTION
**Pull request by ugultopu**
In the cases that the fitness function has been set to minimize, an
individual with NaN fitness was considered be greater than another
individual. This can never be the case since if the fitness of an
individual is NaN, that is not a correct evolution and hence, it cannot
be greater than the other individual.

### CODE REVIEW

**Comment by ugultopu** [comment]
No my changes are the correct version. If I do it the way you tell, an individual with NaN fitness is placed to the end of the list after the list is `sorted()`. So, with your code, the fitnesses are like:

    [1.0, 1.0, 1.0, 0.87, 0.53, 0.27, NaN]

This is not what we want. We want the individual with NaN fitness to be at the beginning of the list (that is, the minimum).

**Comment by ugultopu** [comment]
Also, you say it:

> An individual with NaN fitness must by definition have a worse fitness than an individual with a valid fitness.

Having a "worse fitness" means "being 'less than' the other element". That is, if an individual has a NaN fitness, it should be considered "less than" the other element, no matter if fitness maximization or minimization is being used.

Just try `sorted(individuals)` with your code and print the individuals.

**Comment by ugultopu** [comment]
Another way to think of it: When you apply `sorted ()` it sorts on ascending order by default. I'm the output of `sorted ()`, should an individual with NaN fitness appear towards left (that is, small) or towards right. If you say towards left (which means less than ask other elements), then an individual with a NaN fitness should be considered less than any other individual.

**Comment by mikefenton** [comment]
Sorry for the delay in getting back to you, yup you're right. The wrong logic is in lines 66 and 101.

**Pull request merged**
