### PR TITLE
Santa fe trail

### PR DESCRIPTION
**Pull request by aadeshnpn**
Santa Fe Trail example

### CODE REVIEW

**Comment by dvpfagan** [comment]
Thanks for the pull request, but we won't be accepting it. Ideally we want to demonstrate how to do Santa Fe Ant Trail through the eval/exec of code or else running the phenotype through a parser. The proposed pull request just doesn't fit that model. We also would like to not have to import other frameworks to do the heavy lifting (ie; DEAP). Thanks again and if you feel like changing the code and doing another pull request we welcome the input.

Dave

**Comment by nbro** [comment]
@dvpfagan Ok, but then why didn't you implement this so famous example in PonyGE2? Given that you are familiar with it, it shouldn't be so hard.

**Comment by dvpfagan** [comment]
It’s been widely panned in research in recent years for not being a good
test problem so we focused on the problems identified in the Gecco 2011
survey by White et al.

Dave

**Comment by nbro** [comment]
@dvpfagan This problem can be used to show if the GP implementation can deal with more challenging problems. The web is full of examples of symbolic regression problems, but almost no example that shows that the GP can solve more challenging problems or, at least, be used to solve them. Even if GEGP is not able to solve that problem, I think it's very important to show that GEGP can be used (or not) to solve it.

**Comment by dvpfagan** [comment]
Again I agree but we took a design decision to follow the gecco survey
papers results. Feel free to make an implementation of the problem.

Dave

**Comment by nbro** [comment]
@aadeshnpn Can you please provide more details about **why** you adopted this approach of importing the Deap's `gp` module to implement the Santa Fé example? What issues were you exactly encountering in order to use this approach or what parts of that module did you need to implement the example? I could look at the code, but if you give me a high-level description of your approach and why you did that, I immediately understand which issues one encounters.

**Comment by aadeshnpn** [comment]
Thanks @nbro. Its been a while but as far I can remember Deap framework already has the Santa Fe example implemented. At that time, I was in time crunch so I decided not to implement the Santa Fe problem from scratch but to use the existing implementation. We are just using the AntSimulator class from deap.gp package. They use a nice tree structure to implement the simulator. I am sure we can use their simulator as reference and write the simulator in Numpy.

**Comment by nbro** [comment]
@aadeshnpn I'm familiar with that Deap example and the simulator is not part of the `gp` module. I think you're confused. The simulator is just part of the example itself and could definitely be used in PonyGE without importing any Deap module. So, maybe you should review your code again and tell me exactly why you used `gp`.

**Comment by aadeshnpn** [comment]
Thanks @nbro. Based on my understanding, Class AntSimulator has a module build_routine that takes the program to run the simulator. That module uses the module from GP class called addPrimitive to build a tree and then that tree is used to actually move the ant in the simulator. So the only dependency with Deap is building that tree. 
`       

       ant = AntSimulator(600)

        # Store the phenotype of the individual into code. The phenotype
        # python program sniplet that can be executed by AntSimulator
        code = ind.phenotype

        # Build python partial functions
        routine = ant.build_routine(code)

        # Pass the partial functions to the ant simulator
        ant.run(routine)

        # Return the amount of food eaten
        return ant.eaten`

**Comment by nbro** [comment]
@aadeshnpn I'm not sure which example you're referring to. This example https://github.com/DEAP/deap/blob/master/examples/gp/ant.py has no build_routine function. Maybe you're using an older version of the example. In any case, that's not part of the simulator. `addPrimitive` is only used to build the primitive set, which is not useful in the case of grammatical evolution (but only in tree-based GP).

**Comment by aadeshnpn** [comment]
@nbro. You are right. It was three years ago when I did the SantaFe problem and they had that kind of setup I was referring to. The latest example doesn't have that setup.

**Pull request closed without merging**
